### ISSUE TITLE
Transfer/undeprecate

### ISSUE THREAD

**Issue by dfcreative** [colinmeinke/svg-arc-to-cubic-bezier#1]
Hi @colinmeinke!

I am going to rely on this function in upcoming [regl-scatter2d](https://github.com/dfcreative/regl-scatter2d) component, which is going to be a part of [plotly.js](https://github.com/plotly/plotly.js). Specifically, I need that due to [normalize-svg-path](https://github.com/jkroso/normalize-svg-path/issues/2) issue, requiring [points](https://github.com/colinmeinke/points) would unnecessarily inflate package size.

Since this module is deprecated, do you mind transferring it to me or granting access to the repo/npm name? I don't want to make a fork with the same functionality but dif name like `svg-arc-to-bezier` and clutter npm by that.

Just `npm owner add dfcreative svg-arc-to-cubic-bezier`

Hope for understanding,
Cheers!

**Comment by colinmeinke** [comment]
Hey! Yeah I'm scratching my head wondering why I depreciated it. I seem to have just copied the whole thing into [Points](https://github.com/colinmeinke/points/blob/master/src/arcToBezier.js). I don't know why I thought that was a good idea... I think I'll undepreciate. Are there some issues with this lib that need fixing?

**Comment by dfcreative** [comment]
@colinmeinke well first I am not sure whether browserify/bubleify handles well `export default arcToBezier;` exports, I'd rather go for commonjs way of doing things.
Second, you declare functions as [`const fn = () => {}`](https://github.com/colinmeinke/svg-arc-to-cubic-bezier/blob/master/src/index.js#L112), I'd rather go for classical `function fn () {}`, but that is aesthetics.

In other aspects that works well, so yes, just undeprecating it and mb bumping version to `1.0.0` would be really nice!

**Comment by colinmeinke** [comment]
Oops - didn't see your edit with your third point before closing. Can you open a new issue for that one. I've added cjs, es2016 mod and umd builds, I'm just trying to work out why semantic release isn't doing it's thing, but there should be a v2.0.0 shortly.

**Comment by dfcreative** [comment]
@colinmeinke unfortunately v2.0 exports an object with `default` property which is the function, instead of just function directly. I just wonder are there really use-cases where all that complexity is needed indeed, some convention maybe? Because I naively expect the module just return a function. Is it planned behaviour?

**Comment by colinmeinke** [comment]
@dfcreative no that's just what babel does by default. I've added the [add module exports plugin](https://github.com/59naga/babel-plugin-add-module-exports), so it should behave as you expect now in [version 3](https://github.com/colinmeinke/svg-arc-to-cubic-bezier/releases/tag/v3.0.0).
