### ISSUE TITLE
How to run it in Python?

### ISSUE THREAD

**Issue by qo4on** [colinmeinke/svg-arc-to-cubic-bezier#14]
Is it possible with some wrapper? Or some other way to do that?
I found [this implementation](https://gitlab.com/snippets/1711426). But for the same input arc it returns different result on each run.

**Comment by qwergle** [comment]
You can't (sort of). You can't run JS code in Python, but there are ways to convert JS to Python.

**Comment by qo4on** [comment]
Ok, thank you.
