### ISSUE TITLE
Positional arguments instead of named params

### ISSUE THREAD

**Issue by dfcreative** [colinmeinke/svg-arc-to-cubic-bezier#2]
From #1 

Since we are addressing SVG path `arc` command, a more natural way and stronger convention would be sticking to the same order of arguments as the `arc` command has: `arcToBezier(rx, ry, rotation, large, sweep, x, y)`, rather than named params `arcToBezier({px, py, cx, cy, rx, ry, xAxisRotation, largeArcFlag, sweepFlag})`.

That would be easier to remember and use than looking up for the docs for exact property names for options object, because there is no convention for that.

Probably same can be applied for the result, though curves `x1 y1, x2 y2, x y` order is easier to guess.

Although non critical, just UX.

**Comment by colinmeinke** [comment]
I see what you're saying, and I would agree. However, this function requires the coordinates of where the arc is being drawn from (i.e. the previous points x and y coordiantes). Hence the `px` and `py` (previous points x and y coordinates), and `cx` and `cy` (current points x and y coordinates). I guess this fact renders the proposal invalid. Let me know if I'm missing something here.

I also prefer using an object when there's this many arguments. I like the flexibility of order. Also currently `xAxisRotation`, `largeArcFlag`, `sweepFlag` can all be omitted and are given a default of 0.
