### ISSUE TITLE
Mistake at calculating umag and vmag

### ISSUE THREAD

**Issue by abdulelah** [colinmeinke/svg-arc-to-cubic-bezier#3]
Hi,
Thank you for your work on this, the code will be very helpful if it was documented well.
I noticed that you have an issue at line 43 you didn't set the vmag correctly.
  const umag = Math.sqrt(ux * ux + uy * uy)
  const vmag = Math.sqrt(ux * ux + uy * uy)

**Comment by colinmeinke** [comment]
What should vmag be @abdulelah? I'm cautious to make changes as I lifted this from [SVG path](https://github.com/fontello/svgpath) and don't understand most of it. I see these variables have been changed in SVG path now https://github.com/fontello/svgpath/commit/319b21683ec0af3f73e6cecb86448b1306780a09

**Comment by luciancooper** [comment]
@colinmeinke `vmag` should be fixed to:
```
const umag = Math.sqrt(ux * ux + uy * uy)
const vmag = Math.sqrt(vx * vx + vy * vy)
```
Right now your code is calculating `umag` twice

**Comment by colinmeinke** [comment]
@abdulelah @luciancooper thanks for noticing this. I copied this from a different library, and they have solved this issue by simplifying the code https://github.com/fontello/svgpath/issues/29. I will do the same in the next release.
