### ISSUE TITLE
Release 3.1.1 doesn't have "cjs" folder on it

### ISSUE THREAD

**Issue by nusantara-cloud** [colinmeinke/svg-arc-to-cubic-bezier#6]
Hello,
My program had a dependency to normalize-svg-path module, which in turns uses this module. The latest release of this module (3.1.1), however, breaks it because "cjs" folder is not there, while in package.json, the file to look for dependency resolution is cjs/index.js. I'm WAR-ing the issue by using release 3.0.0, just wanna let the author know. Let me know if you want me to try to make fix, I can also do that. 

Thank you :)

**Comment by colinmeinke** [comment]
@nusantara-cloud oops, that's embarrassing, sorry! Fixed in https://github.com/colinmeinke/svg-arc-to-cubic-bezier/releases/tag/v3.1.2
