### ISSUE TITLE
Incorrect result with integer "M"

### ISSUE THREAD

**Issue by Zonciu** [colinmeinke/svg-arc-to-cubic-bezier#9]
I got a weird result when I set M command with integer, by setting `M 10, 10`, it working not as expected, but `M 10, 10.00000001` works well.
Sample:
https://codepen.io/zonciu/pen/qvKZJo

**Comment by colinmeinke** [comment]
Hi @Zonciu, thanks for the report. This is caused by the same issue as https://github.com/colinmeinke/svg-arc-to-cubic-bezier/issues/10. Reverting to 3.0.0 works as expected. I am reverting the PR that caused this issue.
